export const SET_LIMIT = 'SET_LIMIT';
export const QUANTUM_TICK = 'QUANTUM_TICK';
export const RESTART_QUANTUM = 'RESTART_QUANTUM';
export const DISABLE_QUANTUM = 'DISABLE_QUANTUM';
export const ENABLE_QUANTUM = 'ENABLE_QUANTUM';
