export const SET_RATE = 'SET_RATE';
export const SPAWN_PROCESS_NEW = 'SPAWN_PROCESS_NEW';
export const MOVE_NEW_TO_READY = 'MOVE_NEW_TO_READY';
export const TAKE_ONE_READY_TO_RUNNING = 'TAKE_ONE_READY_TO_RUNNING';
