export const SET_RATE = 'SET_RATE';
export const SPAWN_PROCESS_NEW = 'SPAWN_PROCESS_NEW';
export const MOVE_NEW_TO_READY = 'MOVE_NEW_TO_READY';
export const TAKE_ONE_READY_TO_RUNNING = 'TAKE_ONE_READY_TO_RUNNING';
export const TICK_RUNNING_PROCESS = 'TICK_RUNNING_PROCESS';
export const MOVE_RUNNING_TO_FINISHED = ' MOVE_RUNNING_TO_FINISHED';
